name: 'Setup Environment'
description: 'Sets up Node.js environment and installs dependencies'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
          
    - name: Install project dependencies
      run: npm ci
      shell: bash
