name: 'Generate App ID'
description: |
  Generates an app ID for preview deployments. This action integrates with Deriv's app ID system
  to create unique identifiers for preview deployments.

  Example usage:
    ```yaml
    steps:
      - uses: ./.github/actions/generate-app-id
        with:
          vercel_preview_url: 'https://preview.myapp.dev/feature-123'
          max_retries: 3  # optional, defaults to 5
    ```

outputs:
  app-id:
    description: 'The generated app ID'
    value: ${{ steps.generate_app_id.outputs.app_id }}

inputs:
  vercel_preview_url:
    description: |
      The URL of the preview deployment.
      Must be a valid HTTPS URL (e.g., https://example.com, https://preview.myapp.dev)
    required: true
  max_retries:
    description: 'Maximum number of retry attempts for app ID generation'
    required: false
    default: '5'
  deriv_api_token:
    description: 'Deriv API token for authentication'
    required: true
  deriv_app_id:
    description: 'Deriv App ID for identification'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate Preview URL
      shell: bash
      run: |
        if ! [[ "${{ inputs.vercel_preview_url }}" =~ ^https://[a-zA-Z0-9-]+([.][a-zA-Z0-9-]+)+(:[0-9]+)?(/.*)?$ ]]; then
          echo "Error: Invalid URL format. Must be a valid HTTPS URL"
          exit 1
        fi

    - name: Check required inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.deriv_api_token }}" ] || [ -z "${{ inputs.github_token }}" ]; then
          echo "Error: Required inputs are not available."
          exit 1
        fi

    - name: Generate Deriv App ID
      id: generate_app_id
      uses: deriv-com/deriv-app-id-action@v1
      with:
        DERIV_API_TOKEN: ${{ inputs.deriv_api_token }}
        DERIV_APP_ID: ${{ inputs.deriv_app_id }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        max_retries: ${{ inputs.max_retries }}
        vercel_preview_url: ${{ inputs.vercel_preview_url }}
      continue-on-error: false

    - name: Check Generation Result
      shell: bash
      run: |
        if [ -z "${{ steps.generate_app_id.outputs.app_id }}" ]; then
          echo "Error: Failed to generate app ID after ${{ inputs.max_retries }} attempts"
          exit 1
        fi
    - name: Set output
      shell: bash
      run: echo "app-id=${{ steps.generate_app_id.outputs.app_id }}" >> $GITHUB_OUTPUT
