name: 'Code Quality Assurance'
description: 'Comprehensive quality checks including tests, security scans, and coverage analysis'

runs:
  using: "composite"
  steps:
    # Test Suite Execution
    - name: Execute unit and integration tests
      run: npm test
      shell: bash
      
    # Coverage Analysis (assuming jest or similar test runner)
    - name: Analyze test coverage
      run: npm test -- --coverage
      shell: bash
      
    # Security Scanning (using npm audit)
    - name: Perform security vulnerability scan
      run: npm audit
      shell: bash
      
    # Dependency Analysis
    - name: Check for outdated dependencies
      run: npm outdated || true # Don't fail on outdated deps, just report
      shell: bash
